CREATE TABLE ResetSenhaTokens (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UsuarioId UNIQUEIDENTIFIER NOT NULL,
    Token UNIQUEIDENTIFIER NOT NULL,
    Expiracao DATETIME NOT NULL,
    Usado BIT NOT NULL DEFAULT 0
);