CREATE TABLE UsuarioResetSenha (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UsuarioId UNIQUEIDENTIFIER NOT NULL,
    Token UNIQUEIDENTIFIER NOT NULL,
    DataExpiracao DATETIME NOT NULL,
    Usado BIT NOT NULL DEFAULT 0
);
